image: barichello/godot-ci:mono-3.4

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux
  only:
    - main

window:
  stage: export
  script:
    - godot -v --export "Windows Desktop" ./build/linux/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
    - main

doxygen:
  image: alpine
  stage: deploy
  script:
    - apk update && apk add doxygen
    - doxygen Doxyfile
    - mv docs public/
  artifacts:
    paths:
      - public
  only:
    - main